### ISSUE TITLE
mailman3 - error when starting the mailman3 service and when creating superuser

### ISSUE THREAD

**Issue by TonyCard** [iomarmochtar/mailman3_ei#5]
HI
Please your Support.
in a fresh installation on centos 7.5 the following happened to me
When I send the command to create a user, the following error occurs:
               
[root@servidor ~]# /opt/mailman3/conda/envs/mailman3_ext/bin/python /opt/mailman3/webui/manage.py createsuperuser
Traceback (most recent call last):
  File "/opt/mailman3/webui/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/mailman3/conda/envs/mailman3_ext/lib/python3.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/opt/mailman3/conda/envs/mailman3_ext/lib/python3.7/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/opt/mailman3/conda/envs/mailman3_ext/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/mailman3/conda/envs/mailman3_ext/lib/python3.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/opt/mailman3/conda/envs/mailman3_ext/lib/python3.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/opt/mailman3/conda/envs/mailman3_ext/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/mailman3/conda/envs/mailman3_ext/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 4, in <module>
    from django.contrib.admin.filters import (
  File "/opt/mailman3/conda/envs/mailman3_ext/lib/python3.7/site-packages/django/contrib/admin/filters.py", line 10, in <module>
    from django.contrib.admin.options import IncorrectLookupParameters
  File "/opt/mailman3/conda/envs/mailman3_ext/lib/python3.7/site-packages/django/contrib/admin/options.py", line 12, in <module>
    from django.contrib.admin import helpers, widgets
  File "/opt/mailman3/conda/envs/mailman3_ext/lib/python3.7/site-packages/django/contrib/admin/widgets.py", line 151
    '%s=%s' % (k, v) for k, v in params.items(),
    ^
SyntaxError: Generator expression must be parenthesized

******************************************************************************************************
 
and when the mailman3 service started, the following error occurs:
/opt/mailman3/bin/mailman: line 5: /opt/mailman3/conda/bin/mailman: No such file or directory
/opt/mailman3/bin/mailman: line 5: /opt/mailman3/conda/bin/mailman: No such file or directory

regards.

**Comment by iomarmochtar** [comment]
the root cause of the issue is conda using the latest version of python (3.7) that break some packages. it's been updated by this [commit](https://github.com/iomarmochtar/mailman3_ei/commit/a7fa66e57213ef75a911e74c81430d182d2ed7fa) 

run following code to fetch the latest one.

`cd /opt/mailman3`
`rm -rf conda`
`git pull origin master`
`python install_me.py`
